# Generated by Django 6.0.1 on 2026-09-17 00:13

import django.db.models.deletion
import stepwisemain.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.JSONField(default=stepwisemain.models.default_statement)),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='#000000', max_length=7)),
                ('category', models.CharField(blank=True, default='', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='BugReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('where_it_occurs', models.TextField()),
                ('description', models.TextField()),
                ('how_to_reproduce', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Universe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('update_date', models.DateTimeField(null=True)),
                ('is_shared', models.BooleanField(default=False)),
                ('edges', models.JSONField(default=list)),
                ('plays', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('liked_by', models.ManyToManyField(blank=True, related_name='likedby', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='#000000', max_length=7)),
                ('help_text', models.TextField(blank=True, default='', max_length=2000)),
                ('is_practice', models.BooleanField(default=False)),
                ('proof_steps', models.JSONField(blank=True, default=list)),
                ('coord', models.JSONField(default=stepwisemain.models.default_coord)),
                ('new_special_blocks', models.JSONField(blank=True, default=list)),
                ('universe', models.ForeignKey(default=stepwisemain.models.Universe.get_default_pk, on_delete=django.db.models.deletion.CASCADE, to='stepwisemain.universe')),
            ],
        ),
        migrations.CreateModel(
            name='GameState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('levels_complete', models.JSONField(default=list)),
                ('proof_steps', models.JSONField(default=dict)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('universe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stepwisemain.universe')),
            ],
        ),
        migrations.CreateModel(
            name='Axiom',
            fields=[
                ('proposition_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='stepwisemain.proposition')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stepwisemain.level')),
            ],
            bases=('stepwisemain.proposition',),
        ),
        migrations.CreateModel(
            name='Theorem',
            fields=[
                ('proposition_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='stepwisemain.proposition')),
                ('level', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stepwisemain.level')),
            ],
            bases=('stepwisemain.proposition',),
        ),
    ]
