# Generated by Django 6.0.1 on 2026-10-10 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stepwisemain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='universe',
            name='copy_of',
            field=models.ManyToManyField(blank=True, related_name='copyof', to='stepwisemain.universe'),
        ),
        migrations.AlterField(
            model_name='universe',
            name='edges',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
