# Generated by Django 6.0.1 on 2026-10-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stepwisemain', '0002_universe_copy_of_alter_universe_edges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universe',
            name='copy_of',
            field=models.ManyToManyField(blank=True, related_name='copiedby', to='stepwisemain.universe'),
        ),
    ]
